"use client"

import { useRef } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Download, ImageIcon, FileText, Share2 } from "lucide-react"
import type { PivotResponse } from "@/types"
import { formatNumber } from "@/lib/utils"
import { toast } from "sonner"

type PivotExportProps = {
    pivotData: PivotResponse | null
}

export function PivotExport({ pivotData }: PivotExportProps) {
    const exportRef = useRef<HTMLDivElement>(null)

    const generateTextContent = () => {
        if (!pivotData) return ""

        const lines = [
            `📊 PIVOT LEVELS - ${pivotData.symbol}`,
            `📅 Date: ${pivotData.date}`,
            `⏱️ Timeframe: ${pivotData.timeframe.toUpperCase()}`,
            "",
            "═══ CPR (Central Pivot Range) ═══",
            `TC (Top Central): ₹${formatNumber(pivotData.cpr.tc)}`,
            `Pivot: ₹${formatNumber(pivotData.cpr.pivot)}`,
            `BC (Bottom Central): ₹${formatNumber(pivotData.cpr.bc)}`,
            `Width: ₹${formatNumber(pivotData.cpr.width)} (${pivotData.cpr.width_percent.toFixed(2)}%)`,
            `Classification: ${pivotData.cpr.classification.toUpperCase()}`,
            "",
            "═══ Floor Pivots ═══",
            `R3: ₹${formatNumber(pivotData.floor_pivots.r3)}`,
            `R2: ₹${formatNumber(pivotData.floor_pivots.r2)}`,
            `R1: ₹${formatNumber(pivotData.floor_pivots.r1)}`,
            `Pivot: ₹${formatNumber(pivotData.floor_pivots.pivot)}`,
            `S1: ₹${formatNumber(pivotData.floor_pivots.s1)}`,
            `S2: ₹${formatNumber(pivotData.floor_pivots.s2)}`,
            `S3: ₹${formatNumber(pivotData.floor_pivots.s3)}`,
            "",
            "═══ Fibonacci Levels ═══",
            `0% (High): ₹${formatNumber(pivotData.fibonacci.level_0)}`,
            `23.6%: ₹${formatNumber(pivotData.fibonacci.level_236)}`,
            `38.2%: ₹${formatNumber(pivotData.fibonacci.level_382)}`,
            `50.0%: ₹${formatNumber(pivotData.fibonacci.level_500)}`,
            `61.8% (Golden): ₹${formatNumber(pivotData.fibonacci.level_618)}`,
            `78.6%: ₹${formatNumber(pivotData.fibonacci.level_786)}`,
            `100% (Low): ₹${formatNumber(pivotData.fibonacci.level_100)}`,
        ]

        if (pivotData.fibonacci.ext_1272) {
            lines.push("")
            lines.push("═══ Fibonacci Extensions ═══")
            lines.push(`127.2%: ₹${formatNumber(pivotData.fibonacci.ext_1272)}`)
            if (pivotData.fibonacci.ext_1618) lines.push(`161.8%: ₹${formatNumber(pivotData.fibonacci.ext_1618)}`)
            if (pivotData.fibonacci.ext_2000) lines.push(`200%: ₹${formatNumber(pivotData.fibonacci.ext_2000)}`)
            if (pivotData.fibonacci.ext_2618) lines.push(`261.8%: ₹${formatNumber(pivotData.fibonacci.ext_2618)}`)
        }

        lines.push("")
        lines.push("Generated by Tradeflix Tools")

        return lines.join("\n")
    }

    const handleCopyText = async () => {
        if (!pivotData) {
            toast.error("No pivot data to copy")
            return
        }

        try {
            await navigator.clipboard.writeText(generateTextContent())
            toast.success("Pivot levels copied to clipboard!")
        } catch (error) {
            console.error("Failed to copy:", error)
            toast.error("Failed to copy to clipboard")
        }
    }

    const handleDownloadText = () => {
        if (!pivotData) {
            toast.error("No pivot data to download")
            return
        }

        const content = generateTextContent()
        const blob = new Blob([content], { type: "text/plain" })
        const url = URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = url
        a.download = `pivot-levels-${pivotData.symbol}-${pivotData.date}.txt`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
        toast.success("Text file downloaded!")
    }

    const handleDownloadImage = async () => {
        if (!pivotData || !exportRef.current) {
            toast.error("No pivot data to export")
            return
        }

        try {
            const html2canvas = (await import("html2canvas")).default
            const canvas = await html2canvas(exportRef.current, {
                backgroundColor: "#ffffff",
                scale: 2,
            })

            const url = canvas.toDataURL("image/png")
            const a = document.createElement("a")
            a.href = url
            a.download = `pivot-levels-${pivotData.symbol}-${pivotData.date}.png`
            document.body.appendChild(a)
            a.click()
            document.body.removeChild(a)
            toast.success("Image downloaded!")
        } catch (error) {
            console.error("Failed to generate image:", error)
            toast.error("Failed to generate image. Make sure html2canvas is installed.")
        }
    }

    const handleShare = async () => {
        if (!pivotData) {
            toast.error("No pivot data to share")
            return
        }

        const content = generateTextContent()

        if (navigator.share) {
            try {
                await navigator.share({
                    title: `Pivot Levels - ${pivotData.symbol}`,
                    text: content,
                })
                toast.success("Shared successfully!")
            } catch (error) {
                if ((error as Error).name !== "AbortError") {
                    console.error("Share failed:", error)
                    toast.error("Failed to share")
                }
            }
        } else {
            await handleCopyText()
            toast.info("Share not supported - copied to clipboard instead")
        }
    }

    return (
        <Card className="border-2 hover:shadow-lg transition-all">
            <CardHeader className="bg-gradient-to-r from-cyan-50 to-sky-50 border-b">
                <CardTitle className="flex items-center gap-2">
                    <div className="p-2 bg-cyan-100 rounded-lg">
                        <Download className="h-5 w-5 text-cyan-600" />
                    </div>
                    Export Pivot Levels
                </CardTitle>
                <CardDescription>
                    Download or share pivot levels for morning prep
                </CardDescription>
            </CardHeader>
            <CardContent className="pt-4 space-y-4">
                {!pivotData ? (
                    <div className="text-center py-8 text-muted-foreground">
                        <FileText className="h-12 w-12 mx-auto mb-3 opacity-50" />
                        <p>Calculate pivot levels first to enable export</p>
                    </div>
                ) : (
                    <>
                        {/* Export Buttons */}
                        <div className="grid grid-cols-2 gap-3">
                            <Button variant="outline" onClick={handleCopyText} className="gap-2">
                                <FileText className="h-4 w-4" />
                                Copy Text
                            </Button>
                            <Button variant="outline" onClick={handleDownloadText} className="gap-2">
                                <Download className="h-4 w-4" />
                                Download TXT
                            </Button>
                            <Button variant="outline" onClick={handleDownloadImage} className="gap-2">
                                <ImageIcon className="h-4 w-4" />
                                Download Image
                            </Button>
                            <Button variant="outline" onClick={handleShare} className="gap-2">
                                <Share2 className="h-4 w-4" />
                                Share
                            </Button>
                        </div>

                        {/* Preview Card for Image Export */}
                        <div className="border rounded-lg overflow-hidden">
                            <div className="text-xs text-muted-foreground p-2 bg-muted">Preview (for image export)</div>
                            <div ref={exportRef} className="p-4 bg-white">
                                <div className="text-center mb-4">
                                    <h3 className="text-xl font-bold text-gray-800">📊 {pivotData.symbol} Pivot Levels</h3>
                                    <p className="text-sm text-gray-500">{pivotData.timeframe.toUpperCase()} | {pivotData.date}</p>
                                </div>

                                <div className="grid grid-cols-3 gap-4 text-sm">
                                    {/* CPR */}
                                    <div className="space-y-1">
                                        <div className="font-semibold text-blue-600 border-b pb-1">CPR</div>
                                        <div className="flex justify-between"><span>TC:</span><span className="font-mono">₹{formatNumber(pivotData.cpr.tc)}</span></div>
                                        <div className="flex justify-between"><span>Pivot:</span><span className="font-mono">₹{formatNumber(pivotData.cpr.pivot)}</span></div>
                                        <div className="flex justify-between"><span>BC:</span><span className="font-mono">₹{formatNumber(pivotData.cpr.bc)}</span></div>
                                    </div>

                                    {/* Floor Pivots */}
                                    <div className="space-y-1">
                                        <div className="font-semibold text-purple-600 border-b pb-1">Floor Pivots</div>
                                        <div className="flex justify-between text-red-600"><span>R3:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.r3)}</span></div>
                                        <div className="flex justify-between text-red-500"><span>R2:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.r2)}</span></div>
                                        <div className="flex justify-between text-red-400"><span>R1:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.r1)}</span></div>
                                        <div className="flex justify-between text-green-400"><span>S1:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.s1)}</span></div>
                                        <div className="flex justify-between text-green-500"><span>S2:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.s2)}</span></div>
                                        <div className="flex justify-between text-green-600"><span>S3:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.s3)}</span></div>
                                    </div>

                                    {/* Fibonacci */}
                                    <div className="space-y-1">
                                        <div className="font-semibold text-amber-600 border-b pb-1">Fibonacci</div>
                                        <div className="flex justify-between"><span>0%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_0)}</span></div>
                                        <div className="flex justify-between"><span>38.2%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_382)}</span></div>
                                        <div className="flex justify-between"><span>50%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_500)}</span></div>
                                        <div className="flex justify-between text-amber-600 font-medium"><span>61.8%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_618)}</span></div>
                                        <div className="flex justify-between"><span>100%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_100)}</span></div>
                                    </div>
                                </div>

                                <div className="mt-4 pt-2 border-t text-center text-xs text-gray-400">
                                    Generated by Tradeflix Tools
                                </div>
                            </div>
                        </div>
                    </>
                )}
            </CardContent>
        </Card>
    )
}

export default PivotExport
