"use client"

import { useState, useRef, useEffect } from "react"
import { StyledCard, StyledCardHeader, StyledCardContent } from "@/components/ui/styled-card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible"
import { Calculator, Minus, Sparkles, ArrowRight, Target, RefreshCw, HelpCircle, Download, FileText, ImageIcon, Share2, BookOpen, Settings, TrendingUp, TrendingDown, ChevronDown, Layers, BarChart2 } from "lucide-react"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { pivotApi } from "@/lib/api/pivot"
import type { PivotResponse } from "@/types"
import { formatNumber } from "@/lib/utils"
import { PivotLevelsChart } from "@/components/charts/pivot-levels-chart"
import { MultiTimeframePivots } from "@/components/pivot/MultiTimeframePivots"
import { DistanceCalculator } from "@/components/pivot/DistanceCalculator"
import { SignalDetectionPanel } from "@/components/pivot/SignalDetectionPanel"
import { HistoricalAccuracy } from "@/components/pivot/HistoricalAccuracy"
import { PivotAlerts } from "@/components/pivot/PivotAlerts"
import { IntradayRecalculation } from "@/components/pivot/IntradayRecalculation"
import { toast } from "sonner"

// Export Modal Content Component
function ExportModalContent({ pivotData }: { pivotData: PivotResponse }) {
  const exportRef = useRef<HTMLDivElement>(null)

  const generateTextContent = () => {
    const lines = [
      `📊 PIVOT LEVELS - ${pivotData.symbol}`,
      `📅 Date: ${pivotData.date}`,
      `⏱️ Timeframe: ${pivotData.timeframe.toUpperCase()}`,
      "",
      "═══ CPR (Central Pivot Range) ═══",
      `TC: ₹${formatNumber(pivotData.cpr.tc)}`,
      `Pivot: ₹${formatNumber(pivotData.cpr.pivot)}`,
      `BC: ₹${formatNumber(pivotData.cpr.bc)}`,
      "",
      "═══ Floor Pivots ═══",
      `R3: ₹${formatNumber(pivotData.floor_pivots.r3)}`,
      `R2: ₹${formatNumber(pivotData.floor_pivots.r2)}`,
      `R1: ₹${formatNumber(pivotData.floor_pivots.r1)}`,
      `S1: ₹${formatNumber(pivotData.floor_pivots.s1)}`,
      `S2: ₹${formatNumber(pivotData.floor_pivots.s2)}`,
      `S3: ₹${formatNumber(pivotData.floor_pivots.s3)}`,
      "",
      "═══ Fibonacci ═══",
      `61.8%: ₹${formatNumber(pivotData.fibonacci.level_618)}`,
      "",
      "Generated by Tradeflix Tools",
    ]
    return lines.join("\n")
  }

  const handleCopyText = async () => {
    await navigator.clipboard.writeText(generateTextContent())
    toast.success("Pivot levels copied to clipboard!")
  }

  const handleDownloadText = () => {
    const blob = new Blob([generateTextContent()], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `pivot-levels-${pivotData.symbol}-${pivotData.date}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success("Text file downloaded!")
  }

  const handleDownloadImage = async () => {
    if (!exportRef.current) return
    try {
      const html2canvas = (await import("html2canvas")).default
      const canvas = await html2canvas(exportRef.current, { backgroundColor: "#ffffff", scale: 2 })
      const url = canvas.toDataURL("image/png")
      const a = document.createElement("a")
      a.href = url
      a.download = `pivot-levels-${pivotData.symbol}-${pivotData.date}.png`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      toast.success("Image downloaded!")
    } catch {
      toast.error("Failed to generate image")
    }
  }

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({ title: `Pivot Levels - ${pivotData.symbol}`, text: generateTextContent() })
      } catch { /* user cancelled */ }
    } else {
      await handleCopyText()
    }
  }

  return (
    <div className="space-y-4">
      {/* Export Buttons */}
      <div className="grid grid-cols-2 gap-3">
        <Button variant="outline" onClick={handleCopyText} className="gap-2">
          <FileText className="h-4 w-4" />
          Copy Text
        </Button>
        <Button variant="outline" onClick={handleDownloadText} className="gap-2">
          <Download className="h-4 w-4" />
          Download TXT
        </Button>
        <Button variant="outline" onClick={handleDownloadImage} className="gap-2">
          <ImageIcon className="h-4 w-4" />
          Download Image
        </Button>
        <Button variant="outline" onClick={handleShare} className="gap-2">
          <Share2 className="h-4 w-4" />
          Share
        </Button>
      </div>

      {/* Preview Card */}
      <div className="border rounded-lg overflow-hidden">
        <div className="text-xs text-muted-foreground p-2 bg-muted">Preview (for image export)</div>
        <div ref={exportRef} className="p-4 bg-white">
          <div className="text-center mb-4">
            <h3 className="text-xl font-bold text-gray-800">📊 {pivotData.symbol} Pivot Levels</h3>
            <p className="text-sm text-gray-500">{pivotData.timeframe.toUpperCase()} | {pivotData.date}</p>
          </div>
          <div className="grid grid-cols-3 gap-4 text-sm">
            {/* CPR */}
            <div className="space-y-1">
              <div className="font-semibold text-blue-600 border-b pb-1">CPR</div>
              <div className="flex justify-between"><span>TC:</span><span className="font-mono">₹{formatNumber(pivotData.cpr.tc)}</span></div>
              <div className="flex justify-between"><span>Pivot:</span><span className="font-mono">₹{formatNumber(pivotData.cpr.pivot)}</span></div>
              <div className="flex justify-between"><span>BC:</span><span className="font-mono">₹{formatNumber(pivotData.cpr.bc)}</span></div>
            </div>
            {/* Floor Pivots */}
            <div className="space-y-1">
              <div className="font-semibold text-purple-600 border-b pb-1">Floor Pivots</div>
              <div className="flex justify-between text-red-600"><span>R3:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.r3)}</span></div>
              <div className="flex justify-between text-red-500"><span>R2:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.r2)}</span></div>
              <div className="flex justify-between text-red-400"><span>R1:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.r1)}</span></div>
              <div className="flex justify-between text-green-400"><span>S1:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.s1)}</span></div>
              <div className="flex justify-between text-green-500"><span>S2:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.s2)}</span></div>
              <div className="flex justify-between text-green-600"><span>S3:</span><span className="font-mono">₹{formatNumber(pivotData.floor_pivots.s3)}</span></div>
            </div>
            {/* Fibonacci */}
            <div className="space-y-1">
              <div className="font-semibold text-amber-600 border-b pb-1">Fibonacci</div>
              <div className="flex justify-between"><span>0%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_0)}</span></div>
              <div className="flex justify-between"><span>38.2%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_382)}</span></div>
              <div className="flex justify-between"><span>50%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_500)}</span></div>
              <div className="flex justify-between text-amber-600 font-medium"><span>61.8%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_618)}</span></div>
              <div className="flex justify-between"><span>100%:</span><span className="font-mono">₹{formatNumber(pivotData.fibonacci.level_100)}</span></div>
            </div>
          </div>
          <div className="mt-4 pt-2 border-t text-center text-xs text-gray-400">
            Generated by Tradeflix Tools
          </div>
        </div>
      </div>
    </div>
  )
}

export default function PivotCalculatorPage() {
  const [loading, setLoading] = useState(false)
  const [autoFetchLoading, setAutoFetchLoading] = useState(false)
  const [guideOpen, setGuideOpen] = useState(false)
  const [result, setResult] = useState<PivotResponse | null>(null)
  const [formData, setFormData] = useState({
    symbol: "GOLD",
    high: "",
    low: "",
    close: "",
    timeframe: "daily",
  })

  const handleAutoFetch = async (autoCalculate = false) => {
    setAutoFetchLoading(true)
    try {
      const data = await pivotApi.getAutoPivots(
        formData.symbol,
        formData.timeframe,
        "COMEX"
      )
      const newFormData = {
        ...formData,
        high: data.ohlc.high.toFixed(2),
        low: data.ohlc.low.toFixed(2),
        close: data.ohlc.close.toFixed(2),
      }
      setFormData(newFormData)
      toast.success(`Fetched ${formData.timeframe} OHLC for ${formData.symbol} (${data.ohlc_date})`)

      // Auto-calculate pivots after fetching prices
      if (autoCalculate) {
        await calculatePivots(newFormData)
      }
    } catch (error: unknown) {
      console.error("Error auto-fetching OHLC:", error)
      toast.error("Failed to fetch OHLC data. Please enter values manually.")
    } finally {
      setAutoFetchLoading(false)
    }
  }

  const calculatePivots = async (data: typeof formData) => {
    setLoading(true)
    try {
      const response = await pivotApi.calculate({
        symbol: data.symbol,
        timeframe: data.timeframe,
        ohlc: {
          high: parseFloat(data.high),
          low: parseFloat(data.low),
          close: parseFloat(data.close),
        },
      })
      setResult(response)
      toast.success("Pivot levels calculated successfully!")
    } catch (error: unknown) {
      console.error("Error calculating pivots:", error)
      toast.error("Failed to calculate pivots. Please check your inputs and try again.")
    } finally {
      setLoading(false)
    }
  }

  // Auto-fetch HLC and calculate pivots on page load
  useEffect(() => {
    handleAutoFetch(true)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)

    try {
      const response = await pivotApi.calculate({
        symbol: formData.symbol,
        timeframe: formData.timeframe,
        ohlc: {
          high: parseFloat(formData.high),
          low: parseFloat(formData.low),
          close: parseFloat(formData.close),
        },
      })
      setResult(response)
      toast.success("Pivot levels calculated successfully!")
    } catch (error: unknown) {
      console.error("Error calculating pivots:", error)
      toast.error("Failed to calculate pivots. Please check your inputs and try again.")
      let errorMessage = "Failed to calculate pivots."
      const err = error as { code?: string; message?: string; response?: { data?: { detail?: string }; statusText?: string } }
      if (err.code === "ERR_NETWORK" || err.message?.includes("Network Error")) {
        errorMessage = "Cannot connect to backend API. Please ensure:\n\n1. Backend server is running at http://localhost:8000\n2. Run: cd tools-backend && .venv\\Scripts\\python.exe main.py"
      } else if (err.response) {
        errorMessage = `API Error: ${err.response.data?.detail || err.response.statusText}`
      }
      alert(errorMessage)
    } finally {
      setLoading(false)
    }
  }


  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      {/* Modern Header with Gradient */}
      <div className="relative overflow-hidden rounded-2xl bg-linear-to-br from-blue-500 via-cyan-500 to-teal-500 p-8 text-white shadow-2xl">
        <div className="absolute inset-0 bg-black/10"></div>
        <div className="relative z-10">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3 mb-3">
              <div className="p-3 bg-white/20 backdrop-blur-sm rounded-xl">
                <Calculator className="h-8 w-8" />
              </div>
              <div>
                <h1 className="text-4xl font-bold tracking-tight">Pivot Calculator</h1>
                <div className="flex items-center gap-2 mt-1">
                  <Target className="h-4 w-4" />
                  <span className="text-sm font-medium opacity-90">Precision Trading Levels</span>
                </div>
              </div>
            </div>
            {/* Prominent Export Button */}
            <Dialog>
              <DialogTrigger asChild>
                <Button
                  size="lg"
                  className="bg-white text-blue-600 hover:bg-blue-50 font-semibold shadow-lg"
                  disabled={!result}
                >
                  <Download className="h-5 w-5 mr-2" />
                  Export Pivot Levels
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-2xl">
                <DialogHeader>
                  <DialogTitle className="flex items-center gap-2 text-cyan-600">
                    <Download className="h-5 w-5" />
                    Export Pivot Levels
                  </DialogTitle>
                  <DialogDescription>
                    Download or share pivot levels for morning prep
                  </DialogDescription>
                </DialogHeader>
                {result ? (
                  <ExportModalContent pivotData={result} />
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    <FileText className="h-12 w-12 mx-auto mb-3 opacity-50" />
                    <p>Calculate pivot levels first to enable export</p>
                  </div>
                )}
              </DialogContent>
            </Dialog>
          </div>
          <p className="text-white/90 text-lg max-w-2xl">
            Calculate CPR, Floor, and Fibonacci pivot points for precise intraday trading decisions
          </p>
        </div>
        <div className="absolute -right-10 -bottom-10 w-40 h-40 bg-white/10 rounded-full blur-3xl"></div>
        <div className="absolute -left-10 -top-10 w-40 h-40 bg-white/10 rounded-full blur-3xl"></div>
      </div>

      {/* Understanding Pivot Points - Progressive Disclosure */}
      <Collapsible open={guideOpen} onOpenChange={setGuideOpen}>
        <CollapsibleTrigger asChild>
          <button className="w-full group">
            <div className="relative overflow-hidden rounded-xl bg-linear-to-r from-blue-50 via-cyan-50 to-teal-50 dark:from-blue-950/30 dark:via-cyan-950/30 dark:to-teal-950/30 border border-blue-200/50 dark:border-blue-800/50 p-4 transition-all duration-300 hover:shadow-md hover:border-blue-300 dark:hover:border-blue-700">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-xl bg-linear-to-br from-blue-500 to-cyan-500 text-white shadow-lg shadow-blue-500/25">
                    <BookOpen className="h-5 w-5" />
                  </div>
                  <div className="text-left">
                    <div className="font-semibold text-foreground flex items-center gap-2">
                      Understanding Pivot Points
                      <Badge variant="outline" className="text-xs bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300 border-blue-300 dark:border-blue-700">
                        Guide
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground mt-0.5">
                      Learn about CPR, Floor Pivots, and Fibonacci levels for intraday trading
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-400 group-hover:text-blue-700 dark:group-hover:text-blue-300 transition-colors">
                    {guideOpen ? "Hide Guide" : "Show Guide"}
                  </span>
                  <ChevronDown className={`h-5 w-5 text-blue-600 dark:text-blue-400 transition-transform duration-300 ${guideOpen ? "rotate-180" : ""}`} />
                </div>
              </div>
            </div>
          </button>
        </CollapsibleTrigger>
        <CollapsibleContent className="overflow-hidden data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:slide-up-2 data-[state=open]:slide-down-2">
          <div className="mt-4 rounded-xl border border-blue-200/50 dark:border-blue-800/50 bg-white dark:bg-slate-900 p-6 shadow-sm">
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="relative overflow-hidden p-4 rounded-xl bg-linear-to-br from-cyan-50 to-blue-50 dark:from-cyan-950/30 dark:to-blue-950/30 border border-cyan-200/50 dark:border-cyan-800/50">
                <div className="absolute top-0 right-0 w-12 h-12 bg-cyan-500/10 rounded-full -mr-3 -mt-3" />
                <div className="relative">
                  <div className="font-semibold text-cyan-800 dark:text-cyan-300 flex items-center gap-2 mb-2">
                    <div className="p-1.5 rounded-lg bg-cyan-100 dark:bg-cyan-900/50">
                      <Target className="h-4 w-4 text-cyan-600 dark:text-cyan-400" />
                    </div>
                    CPR (Central Pivot)
                  </div>
                  <p className="text-sm text-cyan-700 dark:text-cyan-400 leading-relaxed">
                    TC, Pivot, BC - Key zone for intraday trend direction and reversals.
                  </p>
                </div>
              </div>
              <div className="relative overflow-hidden p-4 rounded-xl bg-linear-to-br from-purple-50 to-violet-50 dark:from-purple-950/30 dark:to-violet-950/30 border border-purple-200/50 dark:border-purple-800/50">
                <div className="absolute top-0 right-0 w-12 h-12 bg-purple-500/10 rounded-full -mr-3 -mt-3" />
                <div className="relative">
                  <div className="font-semibold text-purple-800 dark:text-purple-300 flex items-center gap-2 mb-2">
                    <div className="p-1.5 rounded-lg bg-purple-100 dark:bg-purple-900/50">
                      <Layers className="h-4 w-4 text-purple-600 dark:text-purple-400" />
                    </div>
                    Floor Pivots
                  </div>
                  <p className="text-sm text-purple-700 dark:text-purple-400 leading-relaxed">
                    R1-R3 resistance, S1-S3 support - Classic support/resistance levels.
                  </p>
                </div>
              </div>
              <div className="relative overflow-hidden p-4 rounded-xl bg-linear-to-br from-amber-50 to-orange-50 dark:from-amber-950/30 dark:to-orange-950/30 border border-amber-200/50 dark:border-amber-800/50">
                <div className="absolute top-0 right-0 w-12 h-12 bg-amber-500/10 rounded-full -mr-3 -mt-3" />
                <div className="relative">
                  <div className="font-semibold text-amber-800 dark:text-amber-300 flex items-center gap-2 mb-2">
                    <div className="p-1.5 rounded-lg bg-amber-100 dark:bg-amber-900/50">
                      <BarChart2 className="h-4 w-4 text-amber-600 dark:text-amber-400" />
                    </div>
                    Fibonacci Levels
                  </div>
                  <p className="text-sm text-amber-700 dark:text-amber-400 leading-relaxed">
                    38.2%, 50%, 61.8% - Golden ratio retracement for precision entries.
                  </p>
                </div>
              </div>
              <div className="relative overflow-hidden p-4 rounded-xl bg-linear-to-br from-emerald-50 to-green-50 dark:from-emerald-950/30 dark:to-green-950/30 border border-emerald-200/50 dark:border-emerald-800/50">
                <div className="absolute top-0 right-0 w-12 h-12 bg-emerald-500/10 rounded-full -mr-3 -mt-3" />
                <div className="relative">
                  <div className="font-semibold text-emerald-800 dark:text-emerald-300 flex items-center gap-2 mb-2">
                    <div className="p-1.5 rounded-lg bg-emerald-100 dark:bg-emerald-900/50">
                      <TrendingUp className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
                    </div>
                    Trading Strategy
                  </div>
                  <p className="text-sm text-emerald-700 dark:text-emerald-400 leading-relaxed">
                    Buy near support, sell near resistance with proper stop losses.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Modern Input Form with consistent header */}
        <StyledCard variant="blue">
          <StyledCardHeader
            icon={Settings}
            title="Input Parameters"
            description="Enter previous day's High, Low, and Close prices"
            variant="blue"
            action={
              <Dialog>
                <DialogTrigger asChild>
                  <Button className="bg-linear-to-r from-blue-500 to-cyan-600 hover:from-blue-600 hover:to-cyan-700 text-white shadow-md">
                    <BookOpen className="h-4 w-4 mr-2" />
                    How to Use
                  </Button>
                </DialogTrigger>
                <DialogContent className="max-w-lg">
                  <DialogHeader>
                    <DialogTitle className="flex items-center gap-3 text-xl">
                      <div className="p-2 bg-linear-to-br from-blue-500 to-cyan-600 rounded-lg text-white">
                        <Settings className="h-5 w-5" />
                      </div>
                      Input Parameters Guide
                    </DialogTitle>
                    <DialogDescription>How to calculate pivot levels</DialogDescription>
                  </DialogHeader>
                  <div className="space-y-4 mt-4">
                    <div className="p-4 rounded-xl bg-blue-50 border border-blue-100">
                      <h4 className="font-bold text-blue-800 mb-2">Step 1: Select Symbol & Timeframe</h4>
                      <p className="text-sm text-blue-700">Choose the commodity and whether you want daily, weekly, or monthly pivots.</p>
                    </div>
                    <div className="p-4 rounded-xl bg-cyan-50 border border-cyan-100">
                      <h4 className="font-bold text-cyan-800 mb-2">Step 2: Get OHLC Data</h4>
                      <p className="text-sm text-cyan-700">Click <strong>&quot;Auto-Fetch&quot;</strong> to get live data from COMEX, or enter values manually.</p>
                    </div>
                    <div className="p-4 rounded-xl bg-teal-50 border border-teal-100">
                      <h4 className="font-bold text-teal-800 mb-2">Step 3: Calculate</h4>
                      <p className="text-sm text-teal-700">Click <strong>&quot;Calculate Pivots&quot;</strong> to generate CPR, Floor Pivots, and Fibonacci levels.</p>
                    </div>
                    <div className="p-3 rounded-lg bg-slate-100 text-sm text-slate-600">
                      <strong>Tip:</strong> For intraday trading, use previous day&apos;s data. For swing trading, use weekly/monthly.
                    </div>
                  </div>
                </DialogContent>
              </Dialog>
            }
          />
          <StyledCardContent>
            <form onSubmit={handleSubmit} className="space-y-4">
              {/* Symbol and Timeframe in a row */}
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="symbol" className="text-slate-600">Symbol</Label>
                  <Select
                    value={formData.symbol}
                    onValueChange={(value: string) =>
                      setFormData({ ...formData, symbol: value })
                    }
                  >
                    <SelectTrigger id="symbol" className="bg-slate-50">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="GOLD">Gold</SelectItem>
                      <SelectItem value="SILVER">Silver</SelectItem>
                      <SelectItem value="CRUDE">Crude Oil</SelectItem>
                      <SelectItem value="COPPER">Copper</SelectItem>
                      <SelectItem value="NATURALGAS">Natural Gas</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="timeframe" className="text-slate-600">Timeframe</Label>
                  <Select
                    value={formData.timeframe}
                    onValueChange={(value: string) =>
                      setFormData({ ...formData, timeframe: value })
                    }
                  >
                    <SelectTrigger id="timeframe" className="bg-slate-50">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="daily">Daily</SelectItem>
                      <SelectItem value="weekly">Weekly</SelectItem>
                      <SelectItem value="monthly">Monthly</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {/* Auto-fetch HLC Button - More prominent */}
              <Button
                type="button"
                variant="outline"
                className="w-full border-2 border-dashed border-cyan-400 hover:border-cyan-500 hover:bg-cyan-50 transition-all duration-300 py-5"
                onClick={() => handleAutoFetch(false)}
                disabled={autoFetchLoading}
              >
                {autoFetchLoading ? (
                  <span className="flex items-center gap-2 text-cyan-600">
                    <RefreshCw className="h-4 w-4 animate-spin" />
                    Fetching Live Data from COMEX...
                  </span>
                ) : (
                  <span className="flex items-center gap-2 text-cyan-600">
                    <RefreshCw className="h-4 w-4" />
                    Auto-Fetch Previous {formData.timeframe.charAt(0).toUpperCase() + formData.timeframe.slice(1)} HLC
                  </span>
                )}
              </Button>

              {/* Price inputs in a visual group */}
              <div className="p-4 rounded-xl bg-slate-50 border space-y-3">
                <div className="text-xs font-medium text-slate-500 uppercase">Price Data</div>
                <div className="grid grid-cols-3 gap-3">
                  <div className="space-y-1">
                    <Label htmlFor="high" className="text-xs text-red-600 font-medium">High</Label>
                    <Input
                      id="high"
                      type="number"
                      step="0.01"
                      placeholder="High"
                      value={formData.high}
                      onChange={(e) => setFormData({ ...formData, high: e.target.value })}
                      required
                      className="bg-white border-red-200 focus:border-red-400"
                    />
                  </div>
                  <div className="space-y-1">
                    <Label htmlFor="low" className="text-xs text-green-600 font-medium">Low</Label>
                    <Input
                      id="low"
                      type="number"
                      step="0.01"
                      placeholder="Low"
                      value={formData.low}
                      onChange={(e) => setFormData({ ...formData, low: e.target.value })}
                      required
                      className="bg-white border-green-200 focus:border-green-400"
                    />
                  </div>
                  <div className="space-y-1">
                    <Label htmlFor="close" className="text-xs text-blue-600 font-medium">Close</Label>
                    <Input
                      id="close"
                      type="number"
                      step="0.01"
                      placeholder="Close"
                      value={formData.close}
                      onChange={(e) => setFormData({ ...formData, close: e.target.value })}
                      required
                      className="bg-white border-blue-200 focus:border-blue-400"
                    />
                  </div>
                </div>
              </div>

              <Button
                type="submit"
                className="w-full bg-linear-to-r from-blue-600 to-cyan-600 hover:from-blue-700 hover:to-cyan-700 text-white font-semibold py-6 rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 group"
                disabled={loading}
              >
                {loading ? (
                  <span className="flex items-center gap-2">
                    <div className="h-5 w-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                    Calculating Levels...
                  </span>
                ) : (
                  <span className="flex items-center gap-2">
                    Calculate Pivots
                    <ArrowRight className="h-5 w-5 group-hover:translate-x-1 transition-transform" />
                  </span>
                )}
              </Button>
            </form>
          </StyledCardContent>
        </StyledCard>

        {/* Modern Results Card with consistent header */}
        <StyledCard variant="green">
          <StyledCardHeader
            icon={Sparkles}
            title="Pivot Levels"
            description={result ? `${result.symbol} - ${result.timeframe.toUpperCase()} pivots` : "Results will appear here after calculation"}
            variant="green"
            action={
              <Dialog>
                <DialogTrigger asChild>
                  <Button className="bg-linear-to-r from-teal-500 to-emerald-600 hover:from-teal-600 hover:to-emerald-700 text-white shadow-md">
                    <BookOpen className="h-4 w-4 mr-2" />
                    Understanding Levels
                  </Button>
                </DialogTrigger>
                <DialogContent className="max-w-2xl">
                  <DialogHeader>
                    <DialogTitle className="flex items-center gap-3 text-xl">
                      <div className="p-2 bg-linear-to-br from-teal-500 to-emerald-600 rounded-lg text-white">
                        <Sparkles className="h-5 w-5" />
                      </div>
                      Pivot Levels Guide
                    </DialogTitle>
                    <DialogDescription>Understanding CPR, Floor Pivots, and Fibonacci</DialogDescription>
                  </DialogHeader>
                  <div className="space-y-4 mt-4">
                    <div className="grid grid-cols-3 gap-3">
                      <div className="p-4 rounded-xl bg-linear-to-br from-blue-50 to-cyan-50 border border-blue-100">
                        <h4 className="font-bold text-blue-800 mb-2">CPR</h4>
                        <p className="text-xs text-blue-700">Central Pivot Range - defines the day&apos;s bias. Narrow CPR = trending, Wide CPR = ranging.</p>
                      </div>
                      <div className="p-4 rounded-xl bg-linear-to-br from-purple-50 to-violet-50 border border-purple-100">
                        <h4 className="font-bold text-purple-800 mb-2">Floor Pivots</h4>
                        <p className="text-xs text-purple-700">Classic S1-S3 and R1-R3 levels. Most widely used by institutional traders.</p>
                      </div>
                      <div className="p-4 rounded-xl bg-linear-to-br from-amber-50 to-orange-50 border border-amber-100">
                        <h4 className="font-bold text-amber-800 mb-2">Fibonacci</h4>
                        <p className="text-xs text-amber-700">Retracement levels. 61.8% (Golden Zone) is the most significant level.</p>
                      </div>
                    </div>
                    <div className="p-4 rounded-xl bg-slate-50 border">
                      <h4 className="font-bold text-slate-800 mb-2">How to Trade</h4>
                      <div className="grid grid-cols-2 gap-3 text-sm">
                        <div className="flex items-start gap-2">
                          <TrendingUp className="h-4 w-4 text-green-600 mt-0.5" />
                          <div>
                            <span className="font-medium text-green-700">Bullish:</span>
                            <span className="text-slate-600"> Price above CPR, buy at supports</span>
                          </div>
                        </div>
                        <div className="flex items-start gap-2">
                          <TrendingDown className="h-4 w-4 text-red-600 mt-0.5" />
                          <div>
                            <span className="font-medium text-red-700">Bearish:</span>
                            <span className="text-slate-600"> Price below CPR, sell at resistances</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </DialogContent>
              </Dialog>
            }
          />
          <StyledCardContent>
            {result ? (
              <div className="animate-in slide-in-from-bottom duration-500">
                <Tabs defaultValue="cpr" className="w-full">
                  <TabsList className="grid w-full grid-cols-3">
                    <TabsTrigger value="cpr">CPR</TabsTrigger>
                    <TabsTrigger value="floor">Floor Pivots</TabsTrigger>
                    <TabsTrigger value="fibonacci">Fibonacci</TabsTrigger>
                  </TabsList>

                  {/* Fixed height container to prevent layout shift on tab switch */}
                  <div className="min-h-[340px]">
                    {/* Modern CPR Levels with inline help */}
                    <TabsContent value="cpr" className="space-y-3">
                      {/* CPR Info Banner */}
                      <div className="text-xs text-muted-foreground bg-slate-50 rounded-lg p-2 border">
                        <span className="font-medium">CPR Formula:</span> Pivot = (H+L+C)/3, BC = (H+L)/2, TC = 2×Pivot - BC
                      </div>
                      <div className="rounded-xl border-2 border-blue-200 bg-blue-50/50 p-4 hover:shadow-md transition-all duration-300">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Minus className="h-4 w-4 text-blue-600" />
                            <span className="font-medium">TC (Top Central)</span>
                            <TooltipProvider>
                              <Tooltip>
                                <TooltipTrigger><HelpCircle className="h-3 w-3 text-muted-foreground" /></TooltipTrigger>
                                <TooltipContent><p className="text-xs max-w-48">Upper boundary of CPR. Price above TC = bullish bias</p></TooltipContent>
                              </Tooltip>
                            </TooltipProvider>
                          </div>
                          <span className="font-mono font-semibold">₹{formatNumber(result.cpr.tc)}</span>
                        </div>
                      </div>
                      <div className="rounded-lg border border-blue-200 bg-blue-50/50 p-3">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Minus className="h-4 w-4 text-blue-600" />
                            <span className="font-medium">Pivot</span>
                            <TooltipProvider>
                              <Tooltip>
                                <TooltipTrigger><HelpCircle className="h-3 w-3 text-muted-foreground" /></TooltipTrigger>
                                <TooltipContent><p className="text-xs max-w-48">Central pivot point. Key level for trend direction</p></TooltipContent>
                              </Tooltip>
                            </TooltipProvider>
                          </div>
                          <span className="font-mono font-semibold">₹{formatNumber(result.cpr.pivot)}</span>
                        </div>
                      </div>
                      <div className="rounded-lg border border-blue-200 bg-blue-50/50 p-3">
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Minus className="h-4 w-4 text-blue-600" />
                            <span className="font-medium">BC (Bottom Central)</span>
                            <TooltipProvider>
                              <Tooltip>
                                <TooltipTrigger><HelpCircle className="h-3 w-3 text-muted-foreground" /></TooltipTrigger>
                                <TooltipContent><p className="text-xs max-w-48">Lower boundary of CPR. Price below BC = bearish bias</p></TooltipContent>
                              </Tooltip>
                            </TooltipProvider>
                          </div>
                          <span className="font-mono font-semibold">₹{formatNumber(result.cpr.bc)}</span>
                        </div>
                      </div>
                      <div className="rounded-lg border bg-muted/50 p-3">
                        <div className="text-sm">
                          <div className="flex justify-between mb-1">
                            <div className="flex items-center gap-1">
                              <span className="text-muted-foreground">CPR Width:</span>
                              <TooltipProvider>
                                <Tooltip>
                                  <TooltipTrigger><HelpCircle className="h-3 w-3 text-muted-foreground" /></TooltipTrigger>
                                  <TooltipContent><p className="text-xs max-w-48">Narrow CPR = trending day. Wide CPR = range-bound day</p></TooltipContent>
                                </Tooltip>
                              </TooltipProvider>
                            </div>
                            <span className="font-medium">₹{formatNumber(result.cpr.width)}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-muted-foreground">Classification:</span>
                            <Badge variant={result.cpr.classification === "narrow" ? "default" : "outline"} className={result.cpr.classification === "narrow" ? "bg-amber-500" : ""}>
                              {result.cpr.classification.toUpperCase()}
                            </Badge>
                          </div>
                        </div>
                      </div>
                    </TabsContent>

                    {/* Floor Pivots with inline help */}
                    <TabsContent value="floor" className="space-y-2">
                      {/* Floor Pivots Info Banner */}
                      <div className="text-xs text-muted-foreground bg-slate-50 rounded-lg p-2 border">
                        <span className="font-medium">Floor Pivots:</span> R1 = 2×P - L, S1 = 2×P - H, R2/S2 = P ± Range
                      </div>
                      {/* Resistance Levels */}
                      <div className="grid grid-cols-3 gap-2">
                        <div className="rounded-lg border border-red-200 bg-red-50/70 p-2 text-center">
                          <div className="text-xs text-red-600 font-medium">R3</div>
                          <div className="font-mono font-semibold text-sm">₹{formatNumber(result.floor_pivots.r3)}</div>
                        </div>
                        <div className="rounded-lg border border-red-200 bg-red-50/70 p-2 text-center">
                          <div className="text-xs text-red-600 font-medium">R2</div>
                          <div className="font-mono font-semibold text-sm">₹{formatNumber(result.floor_pivots.r2)}</div>
                        </div>
                        <div className="rounded-lg border border-red-200 bg-red-50/70 p-2 text-center">
                          <div className="text-xs text-red-600 font-medium">R1</div>
                          <div className="font-mono font-semibold text-sm">₹{formatNumber(result.floor_pivots.r1)}</div>
                        </div>
                      </div>
                      {/* Pivot */}
                      <div className="rounded-lg border-2 border-blue-300 bg-blue-50 p-3 text-center">
                        <div className="text-xs text-blue-600 font-medium">PIVOT</div>
                        <div className="font-mono font-bold text-lg">₹{formatNumber(result.floor_pivots.pivot)}</div>
                      </div>
                      {/* Support Levels */}
                      <div className="grid grid-cols-3 gap-2">
                        <div className="rounded-lg border border-green-200 bg-green-50/70 p-2 text-center">
                          <div className="text-xs text-green-600 font-medium">S1</div>
                          <div className="font-mono font-semibold text-sm">₹{formatNumber(result.floor_pivots.s1)}</div>
                        </div>
                        <div className="rounded-lg border border-green-200 bg-green-50/70 p-2 text-center">
                          <div className="text-xs text-green-600 font-medium">S2</div>
                          <div className="font-mono font-semibold text-sm">₹{formatNumber(result.floor_pivots.s2)}</div>
                        </div>
                        <div className="rounded-lg border border-green-200 bg-green-50/70 p-2 text-center">
                          <div className="text-xs text-green-600 font-medium">S3</div>
                          <div className="font-mono font-semibold text-sm">₹{formatNumber(result.floor_pivots.s3)}</div>
                        </div>
                      </div>
                    </TabsContent>

                    {/* Fibonacci Levels - Compact */}
                    <TabsContent value="fibonacci" className="space-y-2">
                      {/* Fibonacci Info Banner */}
                      <div className="text-xs text-muted-foreground bg-slate-50 rounded-lg p-2 border">
                        <span className="font-medium">Fibonacci:</span> Retracement levels from High to Low. 61.8% = Golden Zone
                      </div>
                      {/* Retracement Levels - Compact Grid */}
                      <div className="grid grid-cols-4 gap-1.5 text-center">
                        <div className="rounded border bg-slate-50 p-1.5">
                          <div className="text-[10px] text-muted-foreground">0%</div>
                          <div className="font-mono text-xs font-medium">₹{formatNumber(result.fibonacci.level_0)}</div>
                        </div>
                        <div className="rounded border bg-slate-50 p-1.5">
                          <div className="text-[10px] text-muted-foreground">23.6%</div>
                          <div className="font-mono text-xs font-medium">₹{formatNumber(result.fibonacci.level_236)}</div>
                        </div>
                        <div className="rounded border bg-slate-50 p-1.5">
                          <div className="text-[10px] text-muted-foreground">38.2%</div>
                          <div className="font-mono text-xs font-medium">₹{formatNumber(result.fibonacci.level_382)}</div>
                        </div>
                        <div className="rounded border bg-slate-50 p-1.5">
                          <div className="text-[10px] text-muted-foreground">50%</div>
                          <div className="font-mono text-xs font-medium">₹{formatNumber(result.fibonacci.level_500)}</div>
                        </div>
                      </div>
                      {/* Golden Zone - Highlighted */}
                      <div className="rounded-lg border-2 border-amber-300 bg-amber-50 p-3 text-center">
                        <div className="text-xs text-amber-600 font-medium">61.8% GOLDEN ZONE</div>
                        <div className="font-mono font-bold text-lg text-amber-700">₹{formatNumber(result.fibonacci.level_618)}</div>
                      </div>
                      <div className="grid grid-cols-2 gap-1.5 text-center">
                        <div className="rounded border bg-slate-50 p-1.5">
                          <div className="text-[10px] text-muted-foreground">78.6%</div>
                          <div className="font-mono text-xs font-medium">₹{formatNumber(result.fibonacci.level_786)}</div>
                        </div>
                        <div className="rounded border bg-slate-50 p-1.5">
                          <div className="text-[10px] text-muted-foreground">100%</div>
                          <div className="font-mono text-xs font-medium">₹{formatNumber(result.fibonacci.level_100)}</div>
                        </div>
                      </div>
                      {/* Extension Levels - Compact */}
                      {(result.fibonacci.ext_1272 || result.fibonacci.ext_1618) && (
                        <div className="pt-2 border-t">
                          <div className="text-[10px] font-medium text-muted-foreground uppercase mb-1.5">Extensions (Targets)</div>
                          <div className="grid grid-cols-4 gap-1.5 text-center">
                            {result.fibonacci.ext_1272 && (
                              <div className="rounded border border-purple-200 bg-purple-50 p-1.5">
                                <div className="text-[10px] text-purple-600">127.2%</div>
                                <div className="font-mono text-xs font-medium text-purple-700">₹{formatNumber(result.fibonacci.ext_1272)}</div>
                              </div>
                            )}
                            {result.fibonacci.ext_1618 && (
                              <div className="rounded border border-purple-200 bg-purple-50 p-1.5">
                                <div className="text-[10px] text-purple-600">161.8%</div>
                                <div className="font-mono text-xs font-medium text-purple-700">₹{formatNumber(result.fibonacci.ext_1618)}</div>
                              </div>
                            )}
                            {result.fibonacci.ext_2000 && (
                              <div className="rounded border border-purple-200 bg-purple-50 p-1.5">
                                <div className="text-[10px] text-purple-600">200%</div>
                                <div className="font-mono text-xs font-medium text-purple-700">₹{formatNumber(result.fibonacci.ext_2000)}</div>
                              </div>
                            )}
                            {result.fibonacci.ext_2618 && (
                              <div className="rounded border border-purple-200 bg-purple-50 p-1.5">
                                <div className="text-[10px] text-purple-600">261.8%</div>
                                <div className="font-mono text-xs font-medium text-purple-700">₹{formatNumber(result.fibonacci.ext_2618)}</div>
                              </div>
                            )}
                          </div>
                        </div>
                      )}
                    </TabsContent>
                  </div>
                </Tabs>
              </div>
            ) : (
              <div className="flex h-64 items-center justify-center text-center">
                <div className="text-muted-foreground animate-pulse">
                  <div className="p-4 bg-linear-to-br from-blue-100 to-cyan-100 rounded-full w-20 h-20 mx-auto mb-4 flex items-center justify-center">
                    <Calculator className="h-10 w-10 text-blue-600" />
                  </div>
                  <p className="text-lg font-medium">Enter values and calculate</p>
                  <p className="text-sm mt-1">to see pivot levels</p>
                </div>
              </div>
            )}
          </StyledCardContent>
        </StyledCard>
      </div>

      {/* Chart Visualization (Full Width), Distance Calculator, and Signal Detection */}
      {result && (
        <>
          {/* Full-width Pivot Levels Chart */}
          <PivotLevelsChart
            cpr={result.cpr}
            floorPivots={result.floor_pivots}
            currentPrice={result.ohlc.close}
          />

          {/* Distance Calculator and Signal Detection side by side */}
          <div className="grid gap-6 lg:grid-cols-2">
            <DistanceCalculator pivotData={result} />
            <SignalDetectionPanel pivotData={result} />
          </div>
        </>
      )}

      {/* Show these sections only after pivots are calculated */}
      {result && (
        <>
          {/* Multi-Timeframe Pivot Analysis */}
          <MultiTimeframePivots />

          {/* Historical Accuracy Analysis */}
          <HistoricalAccuracy />

          {/* Pivot Alerts and Intraday Recalculation side by side */}
          <div className="grid gap-6 lg:grid-cols-2">
            <PivotAlerts pivotData={result} />
            <IntradayRecalculation originalPivotData={result} />
          </div>
        </>
      )}
    </div>
  )
}
