"""Initial database schema

Revision ID: 4fd300483c22
Revises: 
Create Date: 2025-11-11 10:35:08.674096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd300483c22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('contract_month', sa.String(length=10), nullable=True),
    sa.Column('open', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_exchange_timestamp', 'historical_prices', ['symbol', 'exchange', 'timestamp'], unique=False)
    op.create_index('idx_symbol_timeframe_timestamp', 'historical_prices', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_historical_prices_id'), 'historical_prices', ['id'], unique=False)
    op.create_index(op.f('ix_historical_prices_symbol'), 'historical_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_historical_prices_timestamp'), 'historical_prices', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='usertier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('default_symbol', sa.String(), nullable=True),
    sa.Column('default_timeframe', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.Enum('PIVOT_PROXIMITY', 'PIVOT_BREAKOUT', 'ARBITRAGE_THRESHOLD', 'SEASONAL_EVENT', 'CORRELATION_DIVERGENCE', 'COT_EXTREME', 'PRICE_LEVEL', 'CUSTOM', name='alerttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'TRIGGERED', 'EXPIRED', name='alertstatus'), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('delivery_channels', sa.JSON(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('max_triggers', sa.Integer(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('entry_rules', sa.JSON(), nullable=False),
    sa.Column('exit_rules', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('stop_loss', sa.JSON(), nullable=True),
    sa.Column('take_profit', sa.JSON(), nullable=True),
    sa.Column('position_size', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('delivered_via', sa.JSON(), nullable=True),
    sa.Column('delivery_status', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_per_trade', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('slippage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_drawdown_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('total_return', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_return_percent', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('cagr', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('largest_win', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('longest_win_streak', sa.Integer(), nullable=True),
    sa.Column('longest_lose_streak', sa.Integer(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('trades', sa.JSON(), nullable=True),
    sa.Column('monthly_returns', sa.JSON(), nullable=True),
    sa.Column('execution_time_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_id'), 'backtests', ['id'], unique=False)
    op.create_index(op.f('ix_backtests_strategy_id'), 'backtests', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_backtests_user_id'), 'backtests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtests_user_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_strategy_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_id'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_historical_prices_timestamp'), table_name='historical_prices')
    op.drop_index(op.f('ix_historical_prices_symbol'), table_name='historical_prices')
    op.drop_index(op.f('ix_historical_prices_id'), table_name='historical_prices')
    op.drop_index('idx_symbol_timeframe_timestamp', table_name='historical_prices')
    op.drop_index('idx_symbol_exchange_timestamp', table_name='historical_prices')
    op.drop_table('historical_prices')
    # ### end Alembic commands ###
